# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-18 19:33
from __future__ import unicode_literals

import apps.usuarios.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='usuarioPerfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefonoMovil', models.CharField(max_length=13)),
                ('telefonoCasa', models.CharField(max_length=10)),
                ('telefonoTrabajo', models.CharField(max_length=13)),
                ('image', models.ImageField(upload_to=apps.usuarios.models.path)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
