# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-26 19:06
from __future__ import unicode_literals

import apps.usuarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarioperfil',
            name='image',
            field=models.ImageField(upload_to=apps.usuarios.models.path, verbose_name='Foto de Perfil'),
        ),
    ]
