# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 17:24
from __future__ import unicode_literals

import apps.usuarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20161026_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioperfil',
            name='bio',
            field=models.CharField(default='sobre mi', max_length=255),
        ),
        migrations.AddField(
            model_name='usuarioperfil',
            name='inter',
            field=models.CharField(default='mis gustos', max_length=255),
        ),
        migrations.AlterField(
            model_name='usuarioperfil',
            name='image',
            field=models.ImageField(default='Multimaedia/Users/unknow/user.jpg', upload_to=apps.usuarios.models.path, verbose_name='Foto de Perfil'),
        ),
    ]
