# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-17 22:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_resultadousuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interpretacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pmin', models.IntegerField(default=0)),
                ('Pmax', models.IntegerField(default=0)),
                ('diag', models.CharField(max_length=250)),
                ('prueba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.cuestionario')),
            ],
        ),
    ]
