# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_invitado_resultadoguest'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitado',
            name='direccion',
            field=models.CharField(default='local', max_length=255, verbose_name='direccion'),
        ),
        migrations.AddField(
            model_name='invitado',
            name='edad',
            field=models.CharField(default=18, max_length=2, verbose_name='edad'),
        ),
        migrations.AddField(
            model_name='invitado',
            name='sexo',
            field=models.CharField(default='Hombre', max_length=15, verbose_name='sexo'),
        ),
        migrations.AddField(
            model_name='invitado',
            name='telefono',
            field=models.CharField(default='664', max_length=14, verbose_name='telefono'),
        ),
    ]
